### ISSUE TITLE
Init with width: 100% fails

### ISSUE THREAD

**Issue by Domtaholic** [lokku/jquery-nstslider#24] opened 2015-10-29 15:01 UTC
Hi, 

we just noticed following problem:

We have a responsive website for a customer, so we have to set a width: 100% for the less variable @slider-width. That works quite well, but the initial setup ist wrong.

I´ve set following: 

`<div class="nstSlider" data-range_min="0" data-range_max="30000" data-cur_min="0" data-cur_max="30000"> `

result: 
![image](https://cloud.githubusercontent.com/assets/3584433/10822040/96e1e280-7e55-11e5-9535-1448b4433415.png)

then when i first try to scale the max jumps to 16552 and i can slide to the right and get my 30000.

![image](https://cloud.githubusercontent.com/assets/3584433/10822073/c9bef922-7e55-11e5-9a37-d559af04539d.png)

Any help about this would be really nice.

Cheers

**Comment by darksmo** [comment] 2016-04-17 20:20
Hi,

to be honest the slider was not designed with percentage widths in mind, and I cannot reproduce this problem in my demo/index.html page. Do you have any jsfiddle or a zipfile at which the error can be reproduced?

Also, have you already played with the 'refresh' method?

You could try to bind on resize like:

```javascript
$(window).resize(function () {  $('.nstSlider').nstSlider("refresh"); });
```

Then try resizing the window, and you should see the slider updates...

Cheers

**Comment by darksmo** [comment] 2016-10-18 13:02
Closing this one, it was answered

**Closed by darksmo** 2016-10-18 13:02 UTC
